# File: Makefile
# Simple make file to build the executable

TARGETS = 
CC=gcc
CFLAGS = -g -Wall -O3 -save-temps
INCLUDE = -I/lib/modules/`uname -r`/build/include
LIBS = 

all: 
	$(info ************ NO MAKE REQUIRED (PYTHON) ************)


clean:
	rm -f *.o *~ $(TARGETS)
